### ISSUE TITLE
Cannot start conference software as per examples/index.html

### ISSUE THREAD

**Issue by PHPGuus** [eyeson-team/js-docs#10]
Hi there,

I hope you are doing well!

I am encountering a small problem, and cannot find the appropriate documentation to help me.

When I use the index.html as a guide to get started developing my own GUI, and when I look at the React example on github, I understand that I need to call eyeson.start() with a room Access Key that is returned through the API. I retrieved this, and for the instance I'm trying to work, it is NMTtXnaQYwZxmfknL7NPDCDe.

Then, in the JS / Browser, I have registered an event handler through eyeson.onEvent. The first event it receives is a "fetch_room" event that I simply log to the console, and return (as per the example index.html). The second event that the event handler receives is "access_denied", and (obviously) nothing happens.

However, when I browse to the provided Room URL (ending up on eyeson.team), the conference software starts correctly, etc.

This leads me to think that I am missing a crucial step or two. Can you kindly guide me in resolving this initial hurdle, please?

Thank you and best regards,
Guus

**Comment by unused** [comment]
Hi, nice to meet you! I'm doing great, how are you :)

Looks to me that you are doing well with the client side work but it seems your meeting has expired. At least, that's what I would expect from the access denied error. A meeting will expire after a short period of time if no one joins but you can easily join one participant by using the default web GUI provided in the link section (open in browser, continue on the preview page) and join another user which access key you can use for testing. Please note that you have to use the same room identifier ([see parameter id in the eyeson room section](https://eyeson-team.github.io/api/api-reference/#eyeson-room)) so that the users end up in the same meeting.

I hope that fixes your problem, if not please do not hesitate to leave a comment with further details.

Best wishes and good luck,
  Christoph

**Comment by PHPGuus** [comment]
Hi Christoph,

nice to meet you as well, indeed!

Oh that nicely did the trick! Thank you so much.

Sorry that I did not get back to you sooner, I was bogged down doing other projects ;-)

Best wishes, stay safe, and best regards,
Guus
