### ISSUE TITLE
How to leave a conference room

### ISSUE THREAD

**Issue by PHPGuus** [eyeson-team/js-docs#13]
Hi there,

the documentation for the JS library talks about two events when the user "has disconnected" from the room (type "disconnect") and the user "has left" the room (type "remove_user"). The documentation, however, does not clarify what call to make in order for a user to disconnect from a room.

Further, the documentation allures to the fact that we need to make sure that "If providing a presentation feature you should ensure to close any active presentation held by this user, and on demand remember to restore on reconnect.", however it does not indicate how this can be ensured.

Could you guide me in the right direction, please?

Best regards
Guus

**Comment by unused** [comment]
In order to disconnect you can use `eyeson.destroy(); // destroy and cleanup a session` - the events are sent on user side (disconnected) and in context of the participant list (add a user to the list of participants, remove a user from the list of participants). However those are events received and you can close the session easily using the method above.

When using the provided helper and events for document presentation or screenshare we do offer to replace the stream, adapt the layout (show the presenter full in video) and reset this if the participant disconnects for any reason. If you do not use the given helpers and events but build your own screenshare session you have to keep track of this yourself - or not, depending on your requirements. Let's discuss some example: If you utilize the [Screen Capturer API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture) (without using the eyeson package) you receive a desktop stream, then you might want to replace the current participant video with the stream, then adapt the layout so not only the video podium position of the user is replaced but is set to full-video [...] Then you have to take care that the layout is reset in case a user is disconnected [...] This is what we wanted to point out with the comment given.

Best wishes!
