### ISSUE TITLE
Change Audio Settings during ScreenSharing

### ISSUE THREAD

**Issue by jhintringer** [eyeson-team/js-docs#18]
Hy,

is there a way to change the audio input source during my own screen sharing? If I send the event "change_stream" during a screencast, the screencast will continue on client-side, but the remotestream shows the selected camera. No "presentation_ended" event will be triggered. Can you please help me with this?

**What did I do for this to happen:**
```
@eyeson.send({ type: 'start_screen_capture', audio: true, screenStream: null, screen: true })
//  ...
@eyeson.send({ type: 'update_stream', audio: config.audio_enabled, video: config.video_enabled })
```

**What did I expect to happen:**
Audio Input-Source will change, but Videostream keeps the ScreenSource.

**What did happen instead:**
The ScreenCapture continues in the browser, but in the remoteStream my Webcam is shown again. No event "presentation_ended".

**Comment by opusonline** [comment]
Hello @jhintringer,
sorry for the long delay, but we're pretty busy here.
I will have a look and get back to you asap.
Best regards,
Stefan

**Comment by opusonline** [comment]
Hello @jhintringer 
I'm sorry to say, but we don't support changing the audio input during a screenshare since we've noticed some problems when doing this.
Please find another strategy, for example like interrupting the screenshare, change the audio input and then start screenshare again.
Best regards,
Stefan
