### ISSUE TITLE
Never received connected state

### ISSUE THREAD

**Issue by alamgira** [eyeson-team/js-docs#22]
Hello,
1) After calling start, i never received connected status. I am constantly receiving room_ready event type
2) How do i get my local stream after start is called. 
3) Can I start youtube stream without anyone joining?
4) Didn't receive accept event type when i am using another browser to join. 

Switched from start to connect and receiving configuration error
{code: 1, name: "CONFIGURATION_ERROR", parameter: "uri", value: "5fb557e60c81971aeb2366df@integrations.visocon.com", message: "Invalid value "5fb557e60c81971aeb2366df@integrations.visocon.com" for parameter "uri""}

**Comment by unused** [comment]
Hello! Please ensure your meeting is not expired. Therefor only join a meeting if the participant is going to connect immediately, otherwise the meeting will expire after a short period of time. The meeting connected event is received as `accepted`, you can find this also in [the getting started example in the documentation](https://eyeson-team.github.io/js-docs/). The event received also provides the `localStream` on demand, however please note that showing the local stream is only required when using SFU mode so you have to either [disable SFU mode](https://eyeson-team.github.io/api/api-reference/#eyeson-room) or remove the local stream having more than two participants. I'm not sure about your question starting a broadcast without stream but I guess you don't want the participant having to start it. You can create a generic user (that does not need to join) and use the access key to start an RTMP stream. Please double check that you have unique access keys for each participant and the meeting does not expire. The start method is the more convenient method as it does all initialization as well. Best wishes!

**Comment by alamgira** [comment]
Hello,
I am calling start and never received accepted. All it says is room_ready. How do i join on my own room without a participant.

**Comment by alamgira** [comment]
`
var eyesonModule = window.eyeson;
var eyeson = eyesonModule.default;
var start = function() {
	state.connecting = true;
	var access_key= document.getElementById("access_key").value;
	eyeson.onEvent(handleEvent);
	eyeson.start(access_key);
}

 function handleEvent(event) {
 	console.log('[App] Ignore received event:'+ event.type);
  	console.log(event)
	
    if (event.type !== 'accept') {
      return;
    }

    var div = document.getElementById("video-div");
    state.local = event.localStream;
    add_video(div, state.local);
    state.stream = event.remoteStream;
    add_video(div,state.stream);
    state.connecting = false;
}`
I am getting access key by using eyeson php library

`
$eyeson = new Eyeson($api_key);

$room = $eyeson->join($username, $roomname, array("broadcast_available"=> true, "sfu_mode"=> "disabled"));

$access_key = $room->getAccessKey();
$guest_token = $room->getGuestToken();
`
Can you please guide me how to start the video conference from this state and also how will a participant join to this meeting from my site (not using eyeson link)
