### ISSUE TITLE
Error 500 when upload image file on layer

### ISSUE THREAD

**Issue by scredii** [eyeson-team/js-docs#24]
Hi, 

I got error 500 from your server when i try to add an image to layer:

My function:

    addLayer() {
      let formData = new FormData();
      formData.append('file', image1);
      formData.append('url', 'https://eyeson-team.github.io/api/images/eyeson-overlay.png');
      formData.append('insert[title]', 'test');
      formData.append('insert[content]', 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ');
      formData.append('z-index', 1); \n
      axios.post('https://api.eyeson.team/rooms/${this.accessKey}/layers\', formData,{ headers: {'Content-Type': 'multipart/form-data' }})
    }`

return empty response with code 500 with or without FormData.

What's the right way to use this feature ?

I have also tried to use the 'url' field with your example URL, the others field appears but not this one.

Finaly, when i create a custom room from your API and a new user join, the camera are not splitted but i see only the user's one.

my code:

- create new room and enter (admin):

      createRoom() {
      console.log('create room')
      const response = await axios.post(`https://api.eyeson.team/rooms?user[name]=${this.adminName}`, {}, {
        headers: {
          'Authorization': API_TOKEN
        }
      })
      this.accessKey = response.data.access_key
     }

      startStream() {
        console.log('start stream')
        eyeson.onEvent(event => {
          console.debug('[App] Ignore received event:'+ event.type, event);
          if (event.type !== "accept") {
            return;
          }
          let remoteVideo = document.getElementById("remote-video")
          this.addVideo(remoteVideo, event.remoteStream)
          if(event.connectionStatus !== 'connected') {
            return ;
          }
        });
        eyeson.start(this.accessKey);
        }
`
guest access:

    createGuestUser() {
      console.log('create guest user')
      const response = await axios.post(`https://api.eyeson.team/guests/${this.$route.query.guest}`, {
        name: this.guestName
      })
      if (!response.data.access_key) {
        return alert('something was wrong during room creation')
      }
      this.accessKey = response.data.access_key
    }
and the startStream above

Thanks for your help !

**Comment by unused** [comment]
As described in the [documentation](https://eyeson-team.github.io/api/api-reference/#content-integration-aka-layers) please ensure you start the meeting with SFU mode disabled (room option `options[sfu_mode]`, value `disabled`) otherwise no overlay is visible. The parameters given for the layers are either to upload a file, point to an url or to use a predefined generator to set icon, title, content for a simple message. Sending multiple of this variations at once is no valid option. Best wishes!

**Comment by scredii** [comment]
I identified the problem, the camera is not split when we have 2 users in the room (ok when there is one or more than 2 users) and the layer is not available in this configuration. is there a solution to this problem? the sfu mode is indeed deactivated (confirmed by the API feedback)

Regarding the layer, we would like to display a product as well as its description. it's work to display the title and description but not the image: 'insert [icon]', 'https://eyeson-team.github.io/api/images/eyeson-overlay.png' does not work . and 'url' displays a logo at the bottom right as a brand logo, this is not the result we are looking for.

If I use the "image" field, even alone I have a 500 error using a FormData. what should be the format of the image? i am using a png currently.

Thanks for your feedback.

**Comment by unused** [comment]
The [SFU](https://help.eyeson.com/what-is-single-stream-technology) mode has to be disabled, otherwise no overlay is visible (only in recordings, broadcasts, snapshots).

The image `insert` is for simple messages (like a question including topic and some avatar) but is not meant to be used to display information, especially as it cannot be further customized.

The two other options are to upload a file or to point to a remote file. Please note, [as mentioned in the documentation](https://eyeson-team.github.io/api/api-reference/#content-integration-aka-layers), to use a front-layer (overlay) you have to create a 1280x960 alpha interlaced PNG where your content is positioned properly. Have a look at the [example image](https://eyeson-team.github.io/api/images/eyeson-overlay.png) to get an idea about the content. I'd recommend to rather point to a generated image than to upload for ease at use. Uploading seems also to be your problem as the code you posted misses request type `multipart/form-data` and the variable in use (`image1`) might be of wrong type (no file).

Best wishes!
