### ISSUE TITLE
Video Layout issue. Grey boxes around the video

### ISSUE THREAD

**Issue by alamgira** [eyeson-team/js-docs#30]
1) Eyeson showing grey border around the video. How can we get an optimal view without the grey borders.
2) And also the quality of the video seems low even though our wifi is stable. Do we set anything in the configuration to avoid any data loss
3) How can we stack videos top to bottom when second person joins instead of horizontal

Please see the image below
right side is from mobile and has a grey background. How do we fix this. Left side is from desktop
![image](https://user-images.githubusercontent.com/3598597/112014480-4f80c780-8b01-11eb-8af4-b1f19a4c2c8c.png)
****

**Comment by unused** [comment]
You can use the [SFU mode](https://blog.eyeson.com/mcu-sfu-mode) in order to place the remote video screen and the local stream independently. However for more than three participants MCU mode will be used automatically and due to the [single stream](https://help.eyeson.com/what-is-single-stream-technology) you cannot adapt the podium layout for single users. In order to get rid of backgrounds you can set the width and height to crop your client stream.

There is no obvious reason that the quality drops on mobile phones so I'd ask you to double check the network environment, test with other networks and also test against the default web UI.

**Comment by unused** [comment]
Please do not hesitate to leave a comment if you have any further questions on this!

**Comment by alamgira** [comment]
For situation like the picture above, how do we use the podium layou?

**Comment by unused** [comment]
This depends a lot on your requirements. If you always have two participants only, you can use the SFU mode `options[sfu_mode]=ptp` very conveniently.

Here you have to take in mind that one participants remote stream only shows the other participant, so its a good practice to show a second video with the local stream. The local stream is contained in the events received, e.g. [accept](https://eyeson-team.github.io/js-docs/events/#accept).  You can find a working example using the default web UI. Also the [react example](https://github.com/eyeson-team/react-web-gui-example) will show the SFU remote stream **but has no local stream**.

![Screenshot from 2021-03-24 08-14-36](https://user-images.githubusercontent.com/59397/112270389-e40e3580-8c79-11eb-8041-d8e934bdab1a.png)

Another option is to set the layout accordingly. Its likely that you want to control this on server-side, so use one of the users access key or create another and [adapt the layout](https://eyeson-team.github.io/api/api-reference/#layout) on the required view. We have extended the options for layout control yesterday, I've [posted a brief summary on our techblog](https://techblog.eyeson.team/post/podium-layouts/) that shows various examples.

I hope this answers your questions. If you need any further advice leave a comment anytime!
