### ISSUE TITLE
Share screen or file using the javascript Library

### ISSUE THREAD

**Issue by maxou0789** [eyeson-team/js-docs#9]
Hello,
I saw that it is possible to catch a "podium" event when a participant is starting to share his screen or a file.
I would like to send this event using your library so that a user can share a file from our website, but it seems not possible?
thanks

**Comment by unused** [comment]
Hi, you can use the presentation mode when [starting a screen capturing](https://github.com/eyeson-team/react-web-gui-example/blob/master/src/App.js#L70) by using the event rather than handling your own desktop stream using the [web screen capture api](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture). You can also utilize the chat messages to keep track of a presentation lock. To share files it is quite common to work with [canvas streams](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream) and use those as your local stream. You can set a different layout using the [layout options](https://eyeson-team.github.io/api/api-reference/#layout). Do not hesitate to leave a comment if you have any further questions.

Best wishes!
